name: Release to Firefox Add-ons

# Commented out automatic triggers because web-ext sign doesn't work well yet
# on:
#   push:
#     branches: [ main ]
#     tags: [ 'v*' ]

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm install
      
    - name: Lint extension
      run: npx web-ext lint --source-dir=src/
      
    - name: Build extension
      run: |
        cd src
        zip -r ../hide-intercom-extension.zip .
        
    - name: Get version from manifest
      id: version
      run: |
        VERSION=$(node -p "require('./src/manifest.json').version")
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Extension version: $VERSION"
        
    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: hide-intercom-extension.zip
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Submit to Firefox Add-ons (AMO)
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        npx web-ext sign \
          --source-dir=src/ \
          --api-key=${{ secrets.AMO_API_KEY }} \
          --api-secret=${{ secrets.AMO_API_SECRET }} \
          --channel=listed
      env:
        AMO_API_KEY: ${{ secrets.AMO_API_KEY }}
        AMO_API_SECRET: ${{ secrets.AMO_API_SECRET }}
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: extension-build-${{ steps.version.outputs.version }}
        path: |
          hide-intercom-extension.zip
          web-ext-artifacts/
        retention-days: 30
